version: '3.8'

services:
  plex-portal:
    image: ghcr.io/idrinkx/plex-portal:latest
    container_name: plex-portal
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      COOKIE_SECURE: "true"
      DEBUG: "false"

      # Obligatoire: remplacez par une vraie clé longue et aléatoire
      SESSION_SECRET: "change-me-to-a-secure-key"

      # Optionnel: overrides du portail si besoin
      APP_URL: ""
      BASE_PATH: ""
    volumes:
      # Logo et fichiers de config
      - ./config:/config

      # DB Tautulli (lecture seule)
      - /mnt/user/appdata/tautulli:/tautulli-data
    restart: unless-stopped

    # Optionnel: reseau custom
    # networks:
    #   - plex-network

# Optionnel
# networks:
#   plex-network:
#     driver: bridge
