name: Sync public docs and config

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Clone public repo
        run: |
          git clone https://x-access-token:${{ secrets.DOCS_REPO_TOKEN }}@github.com/iDrinkx/plex-portal-docker.git public-repo


      - name: Update version in README.md
        run: |
          VERSION=$(jq -r .version package.json)
          sed -i '0,/^\*\*Version : .\*\*/s//**Version : '"$VERSION"'**/' README.md

      - name: Copy files
        run: |
          cp README.md public-repo/ || true
          cp SETUP.md public-repo/ || true
          cp DOCKER.md public-repo/ || true
          cp UNRAID.md public-repo/ || true
          cp docker-compose.yml public-repo/ || true
          cp CHANGELOG.md public-repo/ || true
          cp LICENSE public-repo/ || true
          cp config/.env.example public-repo/.env.example || true

      - name: Commit and push
        run: |
          cd public-repo
          git config user.name "Plex Portal Bot"
          git config user.email "bot@plex-portal.local"
          git add .
          git commit -m "🔄 Sync docs and config from private repo" || echo "No changes"
          git push
